### ISSUE TITLE
get_catalogs doesn't read private repository

### ISSUE THREAD

**Issue by WatanabeToshimitsu** [dataware-tools/api-helper-python#3]
## Purpose
- bug report

## Description
- 現状 dataware-tools/protocols が private なので，get_catalogs が動かない
- どうやってトークンを注入するのが正しいかわからないのでその辺はお願いしたいです

**Comment by d-hayashi** [comment]
`get_catalogs` 関数は大昔に ( protocols リポジトリが privateでない時に) 実装したものなので使わない方が良いと思います

private リポジトリでも対応できるように実装し直すのもアリですが、 protocols をサブモジュールとして python パッケージに入れ込んでしまう方がてっとり早いかもです
